# Generated by Django 4.1.1 on 2022-10-11 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devs_talk_api_comments', '0002_remove_comment_title_comment_image_reply_likedreply_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='reply',
            field=models.TextField(blank=True, max_length=120, null=True, verbose_name='Reply'),
        ),
    ]
