# Generated by Django 4.1.1 on 2022-10-11 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devs_talk_api_comments', '0003_alter_reply_reply'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clappedreply',
            options={'verbose_name': 'Clapped reply', 'verbose_name_plural': 'Clapped replies'},
        ),
        migrations.AlterModelOptions(
            name='dislikedreply',
            options={'verbose_name': 'Disliked reply', 'verbose_name_plural': 'Disliked replies'},
        ),
        migrations.AlterModelOptions(
            name='likedreply',
            options={'verbose_name': 'Liked reply', 'verbose_name_plural': 'Liked replies'},
        ),
        migrations.AlterModelOptions(
            name='reply',
            options={'ordering': ('-created_at',), 'verbose_name': 'Reply', 'verbose_name_plural': 'Replies'},
        ),
        migrations.AlterField(
            model_name='reply',
            name='reply',
            field=models.TextField(blank=True, max_length=120, null=True),
        ),
    ]
