# Generated by Django 4.1.1 on 2022-10-13 20:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devs_talk_api_app', '0003_alter_customuser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='d_o_b',
            field=models.DateField(default=datetime.date.today, max_length=8),
        ),
    ]
