# Generated by Django 4.1.1 on 2022-10-13 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devs_talk_api_app', '0004_customuser_d_o_b'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='d_o_b',
            new_name='date_of_birth',
        ),
    ]
