# Generated by Django 4.1.1 on 2022-10-19 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devs_talk_api_app', '0011_alter_education_options_alter_work_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='responsibilities',
            field=models.TextField(max_length=255),
        ),
    ]
