# Generated by Django 4.1.1 on 2022-10-19 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devs_talk_api_app', '0013_remove_profile_work_profile_work'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=19, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='education',
            field=models.ManyToManyField(blank=True, to='devs_talk_api_app.education'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='work',
            field=models.ManyToManyField(blank=True, to='devs_talk_api_app.work'),
        ),
    ]
