# Generated by Django 4.1.1 on 2022-10-19 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devs_talk_api_app', '0016_remove_profile_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='education',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='devs_talk_api_app.education'),
        ),
    ]
