# Generated by Django 4.1.1 on 2022-10-27 11:33

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devs_talk_api_app', '0021_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=cloudinary.models.CloudinaryField(default='media/profile/default.jpg', max_length=255, verbose_name='image/profile'),
        ),
    ]
