# Generated by Django 4.1.1 on 2022-11-10 11:45

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devs_talk_api_app', '0024_profile_cover_photo_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cover_photo',
            field=cloudinary.models.CloudinaryField(default=False, max_length=255, null=True, verbose_name='image'),
        ),
    ]
