# Generated by Django 4.1.1 on 2022-11-10 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devs_talk_api_app', '0027_alter_profile_avatar_alter_profile_cover_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cover_photo',
        ),
    ]
