# Generated by Django 4.1.1 on 2022-11-10 17:36

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devs_talk_api_app', '0029_profile_cover_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/bewld-devs/image/upload/v1668100394/devs-talk-python-api-avatars/user_ffxusf.jpg', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cover_photo',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, null=True, verbose_name='image'),
        ),
    ]
