# Generated by Django 4.1.1 on 2022-11-11 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devs_talk_api_app', '0033_alter_follow_follower'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='username',
            field=models.CharField(blank=True, max_length=19, null=True, unique=True),
        ),
    ]
