# Generated by Django 4.1.1 on 2022-11-11 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devs_talk_api_app', '0034_follow_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='username',
            field=models.CharField(max_length=19, null=True),
        ),
    ]
