# Generated by Django 4.1.1 on 2022-11-11 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devs_talk_api_app', '0035_alter_follow_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='username',
        ),
    ]
