# Generated by Django 4.1.1 on 2022-10-01 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=19, null=True, unique=True)),
                ('image', models.FileField(blank=True, max_length=400, null=True, upload_to='')),
                ('language', models.CharField(blank=True, choices=[('Html', 'HTML'), ('Python', 'PYTHON'), ('Javascript', 'JAVASCRIPT'), ('Ruby', 'RUBY')], max_length=55, null=True)),
                ('content', models.TextField(max_length=120, null=True)),
                ('created_at', models.BooleanField(default=False)),
                ('updated_at', models.BooleanField(default=False)),
                ('popularity', models.IntegerField(blank=True, default=0, null=True)),
                ('is_solved', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
