# Generated by Django 4.1.1 on 2022-10-11 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devs_talk_api_feeds', '0002_alter_feed_code_snippet_alter_feed_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='language',
            field=models.CharField(blank=True, choices=[('Vue', 'VUE'), ('Python', 'PYTHON'), ('Javascript', 'JAVASCRIPT'), ('Ruby', 'RUBY'), ('Java', 'JAVA'), ('Rails', 'RAILS'), ('React', 'REACT'), ('Angular', 'ANGULAR'), ('Php', 'PHP'), ('Laravel', 'Laravel'), ('Django', 'DJANGO')], max_length=155, null=True),
        ),
    ]
