# Generated by Django 4.1.1 on 2022-10-06 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devs_talk_api_feeds', '0003_rename_content_feed_code_snippet_feed_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='language',
            field=models.CharField(blank=True, choices=[('Vue', 'VUE'), ('Python', 'PYTHON'), ('Javascript', 'JAVASCRIPT'), ('Ruby', 'RUBY'), ('Java', 'JAVA'), ('Rails', 'RAILS'), ('React', 'REACT'), ('Angular', 'ANGULAR'), ('Php', 'PHP'), ('Laravel', 'Laravel')], max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
